// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ThebookClientProgram;
impl sails_rs::client::Program for ThebookClientProgram {}
pub trait ThebookClient {
    type Env: sails_rs::client::GearEnv;
    fn spot(&self) -> sails_rs::client::Service<spot::SpotImpl, Self::Env>;
    fn amm(&self) -> sails_rs::client::Service<amm::AmmImpl, Self::Env>;
    fn perps_v_1(&self) -> sails_rs::client::Service<perps_v_1::PerpsV1Impl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ThebookClient
    for sails_rs::client::Actor<ThebookClientProgram, E>
{
    type Env = E;
    fn spot(&self) -> sails_rs::client::Service<spot::SpotImpl, Self::Env> {
        self.service(stringify!(Spot))
    }
    fn amm(&self) -> sails_rs::client::Service<amm::AmmImpl, Self::Env> {
        self.service(stringify!(Amm))
    }
    fn perps_v_1(&self) -> sails_rs::client::Service<perps_v_1::PerpsV1Impl, Self::Env> {
        self.service(stringify!(PerpsV1))
    }
}
pub trait ThebookClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<ThebookClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ThebookClientCtors
    for sails_rs::client::Deployment<ThebookClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<ThebookClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod spot {
    use super::*;
    pub trait Spot {
        type Env: sails_rs::client::GearEnv;
        /// Accept a pending admin handover. Callable only by the proposed account.
        fn accept_admin(&mut self) -> sails_rs::client::PendingCall<io::AcceptAdmin, Self::Env>;
        /// Cancel a resting order and refund its unfilled escrow to the caller's
        /// claimable balance. Never gated on the pause switch.
        fn cancel_order(
            &mut self,
            order_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelOrder, Self::Env>;
        /// Stop accepting new orders on a pair. Existing orders can still be cancelled and
        /// proceeds withdrawn. Reversible with `relist_pair` (audit M-14).
        fn delist_pair(
            &mut self,
            pair_id: u64,
        ) -> sails_rs::client::PendingCall<io::DelistPair, Self::Env>;
        /// Curate a new TOKEN/quote market. Admin-only (multisig on mainnet).
        ///
        /// `base_dec`/`quote_dec` are read back from each token's own `VftMetadata`
        /// service and rejected on mismatch — a wrong value would misprice the entire
        /// market by a power of ten, and self-attestation is not a control (audit M-14).
        fn list_pair(
            &mut self,
            base: ActorId,
            quote: ActorId,
            base_dec: u8,
            quote_dec: u8,
        ) -> sails_rs::client::PendingCall<io::ListPair, Self::Env>;
        /// Market buy up to `qty` base, spending at most `max_quote` quote tokens and
        /// requiring at least `min_base_out` base in return.
        ///
        /// `min_base_out` is the slippage bound (audit H-03): without it a taker sweeps
        /// whatever asks happen to exist, which on a thin book is an invitation to pull
        /// quotes and leave a lowball. When the bound is not met the whole budget is
        /// credited back and nothing is filled.
        fn market_buy(
            &mut self,
            pair_id: u64,
            qty: u128,
            max_quote: u128,
            min_base_out: u128,
        ) -> sails_rs::client::PendingCall<io::MarketBuy, Self::Env>;
        /// Market sell `qty` base into the bids, highest-first, requiring at least
        /// `min_quote_out` quote in return (audit H-03). Escrows the base up front and
        /// refunds everything if the bound is not met.
        fn market_sell(
            &mut self,
            pair_id: u64,
            qty: u128,
            min_quote_out: u128,
        ) -> sails_rs::client::PendingCall<io::MarketSell, Self::Env>;
        /// Place a limit order. Escrows the caller's real tokens (a quote-token
        /// `TransferFrom` for a buy, base-token for a sell — requires a prior `approve`),
        /// then crosses the book by price-time priority, crediting fills to claimable
        /// balances. Any unfilled remainder rests.
        ///
        /// Every check that can precede the escrow does; the only post-await failure is
        /// the capacity re-check, which credits the escrow back before returning
        /// (audit C-03, M-08).
        fn place_limit(
            &mut self,
            pair_id: u64,
            side: Side,
            price: u128,
            qty: u128,
        ) -> sails_rs::client::PendingCall<io::PlaceLimit, Self::Env>;
        /// Propose a new admin. Takes effect only when that account calls `accept_admin`,
        /// so a typo is recoverable rather than terminal (audit H-05).
        fn propose_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::ProposeAdmin, Self::Env>;
        /// Re-open a delisted pair. Admin-only.
        fn relist_pair(
            &mut self,
            pair_id: u64,
        ) -> sails_rs::client::PendingCall<io::RelistPair, Self::Env>;
        /// Halt or resume trading. Cancel and withdraw are deliberately never gated on
        /// this, so pausing during an incident cannot trap user funds (audit H-08).
        fn set_paused(
            &mut self,
            paused: bool,
        ) -> sails_rs::client::PendingCall<io::SetPaused, Self::Env>;
        /// Sweep accumulated rounding dust for a token to the admin's claimable balance.
        /// Dust is real, already-held tokens that no claim references (audit M-06).
        fn sweep_dust(
            &mut self,
            token: ActorId,
        ) -> sails_rs::client::PendingCall<io::SweepDust, Self::Env>;
        /// Withdraw `amount` of the caller's claimable `token` to their wallet, or the
        /// full balance when `amount` is `None` (audit L-01). Debits optimistically and
        /// restores the claim if the on-chain transfer fails. Never gated on the pause.
        fn withdraw(
            &mut self,
            token: ActorId,
            amount: Option<u128>,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env>;
        fn get_admin(&self) -> sails_rs::client::PendingCall<io::GetAdmin, Self::Env>;
        /// The caller's withdrawable balance for a given token program.
        fn get_claim(
            &self,
            token: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetClaim, Self::Env>;
        /// The caller's resting orders, paginated. Filled and cancelled orders are not
        /// retained in state — their history is in the event log (audit H-02, M-02).
        fn get_my_orders(
            &self,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetMyOrders, Self::Env>;
        /// Aggregated resting depth for a pair: (bids desc by price, asks asc by price),
        /// each level `(price, remaining_qty)`, capped at `depth` levels per side.
        fn get_orderbook(
            &self,
            pair_id: u64,
            depth: u32,
        ) -> sails_rs::client::PendingCall<io::GetOrderbook, Self::Env>;
        fn get_pair(&self, pair_id: u64) -> sails_rs::client::PendingCall<io::GetPair, Self::Env>;
        /// Curated markets, paginated (audit L-05).
        fn get_pairs(
            &self,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPairs, Self::Env>;
        /// Escrow, dust, and reserve held for a token. With the token's own
        /// `balanceOf(program)` this lets a monitor assert the solvency invariant
        /// without replaying the book (audit M-17).
        fn get_solvency(
            &self,
            token: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetSolvency, Self::Env>;
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env>;
        fn pair_count(&self) -> sails_rs::client::PendingCall<io::PairCount, Self::Env>;
        fn resting_order_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::RestingOrderCount, Self::Env>;
    }
    pub struct SpotImpl;
    impl<E: sails_rs::client::GearEnv> Spot for sails_rs::client::Service<SpotImpl, E> {
        type Env = E;
        fn accept_admin(&mut self) -> sails_rs::client::PendingCall<io::AcceptAdmin, Self::Env> {
            self.pending_call(())
        }
        fn cancel_order(
            &mut self,
            order_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelOrder, Self::Env> {
            self.pending_call((order_id,))
        }
        fn delist_pair(
            &mut self,
            pair_id: u64,
        ) -> sails_rs::client::PendingCall<io::DelistPair, Self::Env> {
            self.pending_call((pair_id,))
        }
        fn list_pair(
            &mut self,
            base: ActorId,
            quote: ActorId,
            base_dec: u8,
            quote_dec: u8,
        ) -> sails_rs::client::PendingCall<io::ListPair, Self::Env> {
            self.pending_call((base, quote, base_dec, quote_dec))
        }
        fn market_buy(
            &mut self,
            pair_id: u64,
            qty: u128,
            max_quote: u128,
            min_base_out: u128,
        ) -> sails_rs::client::PendingCall<io::MarketBuy, Self::Env> {
            self.pending_call((pair_id, qty, max_quote, min_base_out))
        }
        fn market_sell(
            &mut self,
            pair_id: u64,
            qty: u128,
            min_quote_out: u128,
        ) -> sails_rs::client::PendingCall<io::MarketSell, Self::Env> {
            self.pending_call((pair_id, qty, min_quote_out))
        }
        fn place_limit(
            &mut self,
            pair_id: u64,
            side: Side,
            price: u128,
            qty: u128,
        ) -> sails_rs::client::PendingCall<io::PlaceLimit, Self::Env> {
            self.pending_call((pair_id, side, price, qty))
        }
        fn propose_admin(
            &mut self,
            new_admin: ActorId,
        ) -> sails_rs::client::PendingCall<io::ProposeAdmin, Self::Env> {
            self.pending_call((new_admin,))
        }
        fn relist_pair(
            &mut self,
            pair_id: u64,
        ) -> sails_rs::client::PendingCall<io::RelistPair, Self::Env> {
            self.pending_call((pair_id,))
        }
        fn set_paused(
            &mut self,
            paused: bool,
        ) -> sails_rs::client::PendingCall<io::SetPaused, Self::Env> {
            self.pending_call((paused,))
        }
        fn sweep_dust(
            &mut self,
            token: ActorId,
        ) -> sails_rs::client::PendingCall<io::SweepDust, Self::Env> {
            self.pending_call((token,))
        }
        fn withdraw(
            &mut self,
            token: ActorId,
            amount: Option<u128>,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env> {
            self.pending_call((token, amount))
        }
        fn get_admin(&self) -> sails_rs::client::PendingCall<io::GetAdmin, Self::Env> {
            self.pending_call(())
        }
        fn get_claim(
            &self,
            token: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetClaim, Self::Env> {
            self.pending_call((token,))
        }
        fn get_my_orders(
            &self,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetMyOrders, Self::Env> {
            self.pending_call((offset, limit))
        }
        fn get_orderbook(
            &self,
            pair_id: u64,
            depth: u32,
        ) -> sails_rs::client::PendingCall<io::GetOrderbook, Self::Env> {
            self.pending_call((pair_id, depth))
        }
        fn get_pair(&self, pair_id: u64) -> sails_rs::client::PendingCall<io::GetPair, Self::Env> {
            self.pending_call((pair_id,))
        }
        fn get_pairs(
            &self,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPairs, Self::Env> {
            self.pending_call((offset, limit))
        }
        fn get_solvency(
            &self,
            token: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetSolvency, Self::Env> {
            self.pending_call((token,))
        }
        fn is_paused(&self) -> sails_rs::client::PendingCall<io::IsPaused, Self::Env> {
            self.pending_call(())
        }
        fn pair_count(&self) -> sails_rs::client::PendingCall<io::PairCount, Self::Env> {
            self.pending_call(())
        }
        fn resting_order_count(
            &self,
        ) -> sails_rs::client::PendingCall<io::RestingOrderCount, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AcceptAdmin () -> Result<(), super::SpotError>);
        sails_rs::io_struct_impl!(CancelOrder (order_id: u64) -> Result<(), super::SpotError>);
        sails_rs::io_struct_impl!(DelistPair (pair_id: u64) -> Result<(), super::SpotError>);
        sails_rs::io_struct_impl!(ListPair (base: ActorId, quote: ActorId, base_dec: u8, quote_dec: u8) -> Result<u64, super::SpotError>);
        sails_rs::io_struct_impl!(MarketBuy (pair_id: u64, qty: u128, max_quote: u128, min_base_out: u128) -> Result<u64, super::SpotError>);
        sails_rs::io_struct_impl!(MarketSell (pair_id: u64, qty: u128, min_quote_out: u128) -> Result<u64, super::SpotError>);
        sails_rs::io_struct_impl!(PlaceLimit (pair_id: u64, side: super::Side, price: u128, qty: u128) -> Result<u64, super::SpotError>);
        sails_rs::io_struct_impl!(ProposeAdmin (new_admin: ActorId) -> Result<(), super::SpotError>);
        sails_rs::io_struct_impl!(RelistPair (pair_id: u64) -> Result<(), super::SpotError>);
        sails_rs::io_struct_impl!(SetPaused (paused: bool) -> Result<(), super::SpotError>);
        sails_rs::io_struct_impl!(SweepDust (token: ActorId) -> Result<u128, super::SpotError>);
        sails_rs::io_struct_impl!(Withdraw (token: ActorId, amount: Option<u128>) -> Result<u128, super::SpotError>);
        sails_rs::io_struct_impl!(GetAdmin () -> (ActorId,ActorId,));
        sails_rs::io_struct_impl!(GetClaim (token: ActorId) -> u128);
        sails_rs::io_struct_impl!(GetMyOrders (offset: u32, limit: u32) -> Vec<super::SpotOrder>);
        sails_rs::io_struct_impl!(GetOrderbook (pair_id: u64, depth: u32) -> (Vec<(u128,u128,)>,Vec<(u128,u128,)>,));
        sails_rs::io_struct_impl!(GetPair (pair_id: u64) -> Option<super::SpotPair>);
        sails_rs::io_struct_impl!(GetPairs (offset: u32, limit: u32) -> Vec<super::SpotPair>);
        sails_rs::io_struct_impl!(GetSolvency (token: ActorId) -> (u128,u128,u128,));
        sails_rs::io_struct_impl!(IsPaused () -> bool);
        sails_rs::io_struct_impl!(PairCount () -> u64);
        sails_rs::io_struct_impl!(RestingOrderCount () -> u64);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum SpotEvents {
            PairListed {
                pair_id: u64,
                base: ActorId,
                quote: ActorId,
                base_dec: u8,
                quote_dec: u8,
            },
            PairDelisted {
                pair_id: u64,
            },
            PairRelisted {
                pair_id: u64,
            },
            OrderPlaced {
                order_id: u64,
                pair_id: u64,
                trader: ActorId,
                side: Side,
                price: u128,
                qty: u128,
            },
            Trade {
                pair_id: u64,
                taker_order: u64,
                maker_order: u64,
                buyer: ActorId,
                seller: ActorId,
                price: u128,
                qty: u128,
            },
            OrderCancelled {
                order_id: u64,
                pair_id: u64,
                trader: ActorId,
                refunded: u128,
            },
            OrderClosed {
                order_id: u64,
                pair_id: u64,
                trader: ActorId,
                filled: u128,
            },
            Withdrawn {
                who: ActorId,
                token: ActorId,
                amount: u128,
            },
            DustSwept {
                token: ActorId,
                amount: u128,
            },
            PausedSet {
                paused: bool,
            },
            AdminProposed {
                pending: ActorId,
            },
            AdminChanged {
                admin: ActorId,
            },
        }
        impl sails_rs::client::Event for SpotEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "PairListed",
                "PairDelisted",
                "PairRelisted",
                "OrderPlaced",
                "Trade",
                "OrderCancelled",
                "OrderClosed",
                "Withdrawn",
                "DustSwept",
                "PausedSet",
                "AdminProposed",
                "AdminChanged",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for SpotImpl {
            type Event = SpotEvents;
        }
    }
}

pub mod amm {
    use super::*;
    pub trait Amm {
        type Env: sails_rs::client::GearEnv;
        /// Deposit both tokens and receive LP shares.
        ///
        /// `min_shares` is the caller's bound: deposits are minted at the pool's ratio at
        /// execution time, which another trade can move between signing and landing.
        /// Requires a prior `approve` of each token.
        fn add_liquidity(
            &mut self,
            pool_id: u64,
            amount_a: u128,
            amount_b: u128,
            min_shares: u128,
        ) -> sails_rs::client::PendingCall<io::AddLiquidity, Self::Env>;
        /// Create a pool for a token pair. Admin-only, like spot listing: a pool is a
        /// curated market, not something anyone can conjure.
        ///
        /// Decimals are verified against each token's own `VftMetadata` and rejected on
        /// mismatch, for the same reason listing does it (audit M-14).
        fn create_pool(
            &mut self,
            token_a: ActorId,
            token_b: ActorId,
            dec_a: u8,
            dec_b: u8,
        ) -> sails_rs::client::PendingCall<io::CreatePool, Self::Env>;
        /// Burn shares and take back the corresponding fraction of both reserves,
        /// including the fees accrued into them.
        ///
        /// Credited to claimable balances (withdraw with `Spot/Withdraw`), and never
        /// gated on the pause or on the pool being active: a provider must always be
        /// able to leave.
        fn remove_liquidity(
            &mut self,
            pool_id: u64,
            shares: u128,
            min_a: u128,
            min_b: u128,
        ) -> sails_rs::client::PendingCall<io::RemoveLiquidity, Self::Env>;
        /// Stop or resume deposits and swaps on a pool. Removing liquidity is never
        /// blocked, so delisting cannot strand a provider's funds.
        fn set_pool_active(
            &mut self,
            pool_id: u64,
            active: bool,
        ) -> sails_rs::client::PendingCall<io::SetPoolActive, Self::Env>;
        /// Swap `amount_in` of `token_in` for the other token, receiving at least
        /// `min_amount_out`. Requires a prior `approve` of `token_in`.
        ///
        /// The output is credited to the caller's claimable balance, on the same
        /// settlement path as spot, so no swap depends on a transfer succeeding mid-way.
        fn swap(
            &mut self,
            pool_id: u64,
            token_in: ActorId,
            amount_in: u128,
            min_amount_out: u128,
        ) -> sails_rs::client::PendingCall<io::Swap, Self::Env>;
        fn get_pool(&self, pool_id: u64) -> sails_rs::client::PendingCall<io::GetPool, Self::Env>;
        fn get_pools(
            &self,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPools, Self::Env>;
        /// The caller's LP shares in a pool, and what they are currently worth.
        fn get_position(
            &self,
            pool_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetPosition, Self::Env>;
        /// Quote a swap without executing it: `(amount_out, fee)`.
        fn quote_swap(
            &self,
            pool_id: u64,
            token_in: ActorId,
            amount_in: u128,
        ) -> sails_rs::client::PendingCall<io::QuoteSwap, Self::Env>;
    }
    pub struct AmmImpl;
    impl<E: sails_rs::client::GearEnv> Amm for sails_rs::client::Service<AmmImpl, E> {
        type Env = E;
        fn add_liquidity(
            &mut self,
            pool_id: u64,
            amount_a: u128,
            amount_b: u128,
            min_shares: u128,
        ) -> sails_rs::client::PendingCall<io::AddLiquidity, Self::Env> {
            self.pending_call((pool_id, amount_a, amount_b, min_shares))
        }
        fn create_pool(
            &mut self,
            token_a: ActorId,
            token_b: ActorId,
            dec_a: u8,
            dec_b: u8,
        ) -> sails_rs::client::PendingCall<io::CreatePool, Self::Env> {
            self.pending_call((token_a, token_b, dec_a, dec_b))
        }
        fn remove_liquidity(
            &mut self,
            pool_id: u64,
            shares: u128,
            min_a: u128,
            min_b: u128,
        ) -> sails_rs::client::PendingCall<io::RemoveLiquidity, Self::Env> {
            self.pending_call((pool_id, shares, min_a, min_b))
        }
        fn set_pool_active(
            &mut self,
            pool_id: u64,
            active: bool,
        ) -> sails_rs::client::PendingCall<io::SetPoolActive, Self::Env> {
            self.pending_call((pool_id, active))
        }
        fn swap(
            &mut self,
            pool_id: u64,
            token_in: ActorId,
            amount_in: u128,
            min_amount_out: u128,
        ) -> sails_rs::client::PendingCall<io::Swap, Self::Env> {
            self.pending_call((pool_id, token_in, amount_in, min_amount_out))
        }
        fn get_pool(&self, pool_id: u64) -> sails_rs::client::PendingCall<io::GetPool, Self::Env> {
            self.pending_call((pool_id,))
        }
        fn get_pools(
            &self,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPools, Self::Env> {
            self.pending_call((offset, limit))
        }
        fn get_position(
            &self,
            pool_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetPosition, Self::Env> {
            self.pending_call((pool_id,))
        }
        fn quote_swap(
            &self,
            pool_id: u64,
            token_in: ActorId,
            amount_in: u128,
        ) -> sails_rs::client::PendingCall<io::QuoteSwap, Self::Env> {
            self.pending_call((pool_id, token_in, amount_in))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddLiquidity (pool_id: u64, amount_a: u128, amount_b: u128, min_shares: u128) -> Result<u128, super::AmmError>);
        sails_rs::io_struct_impl!(CreatePool (token_a: ActorId, token_b: ActorId, dec_a: u8, dec_b: u8) -> Result<u64, super::AmmError>);
        sails_rs::io_struct_impl!(RemoveLiquidity (pool_id: u64, shares: u128, min_a: u128, min_b: u128) -> Result<(u128,u128,), super::AmmError>);
        sails_rs::io_struct_impl!(SetPoolActive (pool_id: u64, active: bool) -> Result<(), super::AmmError>);
        sails_rs::io_struct_impl!(Swap (pool_id: u64, token_in: ActorId, amount_in: u128, min_amount_out: u128) -> Result<u128, super::AmmError>);
        sails_rs::io_struct_impl!(GetPool (pool_id: u64) -> Option<super::AmmPool>);
        sails_rs::io_struct_impl!(GetPools (offset: u32, limit: u32) -> Vec<super::AmmPool>);
        sails_rs::io_struct_impl!(GetPosition (pool_id: u64) -> (u128,u128,u128,));
        sails_rs::io_struct_impl!(QuoteSwap (pool_id: u64, token_in: ActorId, amount_in: u128) -> (u128,u128,));
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum AmmEvents {
            PoolCreated {
                pool_id: u64,
                token_a: ActorId,
                token_b: ActorId,
            },
            PoolActiveSet {
                pool_id: u64,
                active: bool,
            },
            LiquidityAdded {
                pool_id: u64,
                provider: ActorId,
                amount_a: u128,
                amount_b: u128,
                shares: u128,
            },
            LiquidityRemoved {
                pool_id: u64,
                provider: ActorId,
                amount_a: u128,
                amount_b: u128,
                shares: u128,
            },
            Swapped {
                pool_id: u64,
                trader: ActorId,
                token_in: ActorId,
                amount_in: u128,
                token_out: ActorId,
                amount_out: u128,
                fee: u128,
            },
        }
        impl sails_rs::client::Event for AmmEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "PoolCreated",
                "PoolActiveSet",
                "LiquidityAdded",
                "LiquidityRemoved",
                "Swapped",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for AmmImpl {
            type Event = AmmEvents;
        }
    }
}

pub mod perps_v_1 {
    use super::*;
    pub trait PerpsV1 {
        type Env: sails_rs::client::GearEnv;
        /// Admin: list a perp market. `max_oi` is required and must be non-zero — the
        /// reserve's exposure is bounded at creation, not by a remembered follow-up
        /// (audit M-03).
        fn add_market(
            &mut self,
            symbol: String,
            max_oi: u128,
        ) -> sails_rs::client::PendingCall<io::AddMarket, Self::Env>;
        /// Close your position, settling PnL and funding against the reserve and
        /// crediting the payout to your claimable collateral (withdraw via
        /// `Spot/Withdraw`). Never gated on the pause switch, and never gated on a live
        /// keeper once the feed has been dead past `MARK_EXIT_AGE`.
        fn close_position(
            &mut self,
            position_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env>;
        /// Admin: fund the house reserve with real collateral (requires a prior `approve`).
        fn fund_reserve(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::FundReserve, Self::Env>;
        /// Permissionless liquidation once equity falls to maintenance margin.
        ///
        /// The liquidator's fee is paid from residual equity and topped up from the
        /// reserve when equity has gapped away. Capping the fee at residual equity meant
        /// it vanished exactly when liquidation mattered most, so nobody would run a bot
        /// for it (audit L-07).
        fn liquidate(
            &mut self,
            position_id: u64,
        ) -> sails_rs::client::PendingCall<io::Liquidate, Self::Env>;
        /// Open an isolated-margin position. Escrows `margin` of the collateral token
        /// (requires a prior `approve`); notional = margin * leverage at the mark.
        ///
        /// Everything that can be checked before the escrow is checked before it. The two
        /// post-await re-checks exist because the await yields to other messages, and
        /// both credit the margin back before returning (audit C-03, M-08).
        fn open_position(
            &mut self,
            market_id: u64,
            is_long: bool,
            margin: u128,
            leverage: u32,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env>;
        /// Admin: set the collateral (settlement) token — the USDT VFT program.
        fn set_collateral(
            &mut self,
            token: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetCollateral, Self::Env>;
        /// Admin: set the keeper account allowed to push mark prices. The zero address is
        /// rejected — accepting it silently left admin as the sole mark authority
        /// (audit L-04).
        fn set_keeper(
            &mut self,
            keeper: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetKeeper, Self::Env>;
        /// Keeper: publish the mark price for a market.
        ///
        /// Bounded to `MAX_MARK_DEVIATION_BPS` from the previous mark, so a compromised
        /// keeper cannot reprice the book in a single transaction and liquidate it
        /// (audit H-04). The bound is skipped only for the first mark, and once the feed
        /// is stale past `MARK_EXIT_AGE` — by then positions can already exit at entry,
        /// so a fresh start is not a lever over anyone.
        fn set_mark(
            &mut self,
            market_id: u64,
            price: u128,
        ) -> sails_rs::client::PendingCall<io::SetMark, Self::Env>;
        /// Admin: cap open interest per side on a market.
        fn set_market_cap(
            &mut self,
            market_id: u64,
            max_oi: u128,
        ) -> sails_rs::client::PendingCall<io::SetMarketCap, Self::Env>;
        /// Admin: withdraw reserve profit to the admin's claimable collateral.
        ///
        /// Capped at the amount above current liability, so solvency is a contract
        /// invariant instead of operator discipline — draining the reserve used to
        /// silently truncate what winning traders received rather than failing loudly
        /// (audit H-05).
        fn withdraw_reserve(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawReserve, Self::Env>;
        /// `(collateral token, keeper)`. The collateral token is what margin is escrowed
        /// in, so a client can attribute locked margin to the right token instead of
        /// showing a wallet balance that silently dropped.
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
        /// Liquidation price for a position (0 if none).
        fn get_liq_price(
            &self,
            position_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetLiqPrice, Self::Env>;
        fn get_markets(&self) -> sails_rs::client::PendingCall<io::GetMarkets, Self::Env>;
        /// A trader's open positions with PnL at the current mark, paginated (audit L-05):
        /// `(id, market_id, is_long, notional, entry, margin, leverage, pnl)`.
        fn get_positions(
            &self,
            owner: ActorId,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env>;
        fn get_reserve(&self) -> sails_rs::client::PendingCall<io::GetReserve, Self::Env>;
        /// Reserve health: `(reserve, liability, coverage_bps)`. Surfaced so a trader can
        /// see the reserve is thin *before* entering, rather than discovering it as a
        /// truncated payout on the way out (audit M-04).
        fn get_reserve_health(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetReserveHealth, Self::Env>;
    }
    pub struct PerpsV1Impl;
    impl<E: sails_rs::client::GearEnv> PerpsV1 for sails_rs::client::Service<PerpsV1Impl, E> {
        type Env = E;
        fn add_market(
            &mut self,
            symbol: String,
            max_oi: u128,
        ) -> sails_rs::client::PendingCall<io::AddMarket, Self::Env> {
            self.pending_call((symbol, max_oi))
        }
        fn close_position(
            &mut self,
            position_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env> {
            self.pending_call((position_id,))
        }
        fn fund_reserve(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::FundReserve, Self::Env> {
            self.pending_call((amount,))
        }
        fn liquidate(
            &mut self,
            position_id: u64,
        ) -> sails_rs::client::PendingCall<io::Liquidate, Self::Env> {
            self.pending_call((position_id,))
        }
        fn open_position(
            &mut self,
            market_id: u64,
            is_long: bool,
            margin: u128,
            leverage: u32,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env> {
            self.pending_call((market_id, is_long, margin, leverage))
        }
        fn set_collateral(
            &mut self,
            token: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetCollateral, Self::Env> {
            self.pending_call((token,))
        }
        fn set_keeper(
            &mut self,
            keeper: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetKeeper, Self::Env> {
            self.pending_call((keeper,))
        }
        fn set_mark(
            &mut self,
            market_id: u64,
            price: u128,
        ) -> sails_rs::client::PendingCall<io::SetMark, Self::Env> {
            self.pending_call((market_id, price))
        }
        fn set_market_cap(
            &mut self,
            market_id: u64,
            max_oi: u128,
        ) -> sails_rs::client::PendingCall<io::SetMarketCap, Self::Env> {
            self.pending_call((market_id, max_oi))
        }
        fn withdraw_reserve(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::WithdrawReserve, Self::Env> {
            self.pending_call((amount,))
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
        fn get_liq_price(
            &self,
            position_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetLiqPrice, Self::Env> {
            self.pending_call((position_id,))
        }
        fn get_markets(&self) -> sails_rs::client::PendingCall<io::GetMarkets, Self::Env> {
            self.pending_call(())
        }
        fn get_positions(
            &self,
            owner: ActorId,
            offset: u32,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env> {
            self.pending_call((owner, offset, limit))
        }
        fn get_reserve(&self) -> sails_rs::client::PendingCall<io::GetReserve, Self::Env> {
            self.pending_call(())
        }
        fn get_reserve_health(
            &self,
        ) -> sails_rs::client::PendingCall<io::GetReserveHealth, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddMarket (symbol: String, max_oi: u128) -> Result<u64, super::PerpsError>);
        sails_rs::io_struct_impl!(ClosePosition (position_id: u64) -> Result<(u128,i128,), super::PerpsError>);
        sails_rs::io_struct_impl!(FundReserve (amount: u128) -> Result<u128, super::PerpsError>);
        sails_rs::io_struct_impl!(Liquidate (position_id: u64) -> Result<(), super::PerpsError>);
        sails_rs::io_struct_impl!(OpenPosition (market_id: u64, is_long: bool, margin: u128, leverage: u32) -> Result<u64, super::PerpsError>);
        sails_rs::io_struct_impl!(SetCollateral (token: ActorId) -> Result<(), super::PerpsError>);
        sails_rs::io_struct_impl!(SetKeeper (keeper: ActorId) -> Result<(), super::PerpsError>);
        sails_rs::io_struct_impl!(SetMark (market_id: u64, price: u128) -> Result<(), super::PerpsError>);
        sails_rs::io_struct_impl!(SetMarketCap (market_id: u64, max_oi: u128) -> Result<(), super::PerpsError>);
        sails_rs::io_struct_impl!(WithdrawReserve (amount: u128) -> Result<u128, super::PerpsError>);
        sails_rs::io_struct_impl!(GetConfig () -> (ActorId,ActorId,));
        sails_rs::io_struct_impl!(GetLiqPrice (position_id: u64) -> u128);
        sails_rs::io_struct_impl!(GetMarkets () -> Vec<super::PerpMarket>);
        sails_rs::io_struct_impl!(GetPositions (owner: ActorId, offset: u32, limit: u32) -> Vec<(u64,u64,bool,u128,u128,u128,u32,i128,)>);
        sails_rs::io_struct_impl!(GetReserve () -> u128);
        sails_rs::io_struct_impl!(GetReserveHealth () -> (u128,u128,u128,));
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum PerpsV1Events {
            MarketAdded {
                market_id: u64,
                symbol: String,
                max_oi: u128,
            },
            MarketCapSet {
                market_id: u64,
                max_oi: u128,
            },
            MarkSet {
                market_id: u64,
                price: u128,
                block: u32,
            },
            PositionOpened {
                position_id: u64,
                market_id: u64,
                owner: ActorId,
                is_long: bool,
                notional: u128,
                entry: u128,
                margin: u128,
                leverage: u32,
            },
            PositionClosed {
                position_id: u64,
                owner: ActorId,
                payout: u128,
                pnl: i128,
                funding: i128,
                at_entry: bool,
            },
            PositionLiquidated {
                position_id: u64,
                owner: ActorId,
                liquidator: ActorId,
                to_owner: u128,
                fee: u128,
            },
            ReserveFunded {
                amount: u128,
                reserve: u128,
            },
            ReserveWithdrawn {
                amount: u128,
                reserve: u128,
            },
            KeeperSet {
                keeper: ActorId,
            },
            CollateralSet {
                token: ActorId,
            },
        }
        impl sails_rs::client::Event for PerpsV1Events {
            const EVENT_NAMES: &'static [Route] = &[
                "MarketAdded",
                "MarketCapSet",
                "MarkSet",
                "PositionOpened",
                "PositionClosed",
                "PositionLiquidated",
                "ReserveFunded",
                "ReserveWithdrawn",
                "KeeperSet",
                "CollateralSet",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for PerpsV1Impl {
            type Event = PerpsV1Events;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum SpotError {
    /// Caller is not the admin/multisig.
    NotAdmin,
    /// Zero price/qty, unknown token, or other malformed input.
    BadParams,
    /// A pair with the same (base, quote) already exists — in either orientation.
    PairExists,
    /// No pair with that id.
    NoPair,
    /// Pair exists but is delisted; no new orders accepted.
    PairInactive,
    /// The global resting-order cap is reached.
    BookFull,
    /// No order with that id.
    NoOrder,
    /// Caller does not own that order.
    NotOwner,
    /// Nothing to withdraw for that token.
    NothingToClaim,
    /// The on-chain VFT transfer failed (bad allowance/balance, or program error).
    TransferFailed,
    /// Trading is paused. Cancel and withdraw remain open.
    Paused,
    /// The fill would be worse than the caller's stated slippage bound.
    SlippageExceeded,
    /// An amount overflowed u128. Trapping beats a silently wrong number.
    Overflow,
    /// The token's on-chain decimals do not match the value supplied at listing.
    DecimalsMismatch,
    /// No pending admin, or the caller is not the pending admin.
    NotPendingAdmin,
}
/// `Ord` matters: `Side` is part of the spot price-level index key
/// `(pair_id, side, price)`, which is what makes matching walk levels instead of
/// every order ever placed.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Side {
    Buy,
    Sell,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SpotOrder {
    pub id: u64,
    pub pair_id: u64,
    pub trader: ActorId,
    pub side: Side,
    /// Quote smallest-units per one whole base token (per 10^base_dec base units).
    pub price: u128,
    /// Order size in base token smallest units.
    pub qty: u128,
    /// Filled base amount so far.
    pub filled: u128,
    pub status: SpotStatus,
    /// Tokens escrowed when the order was placed (quote for a buy, base for a sell).
    pub escrowed: u128,
    /// How much of `escrowed` has been paid out or refunded. The remainder at
    /// removal time is rounding dust (audit M-06).
    pub released: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum SpotStatus {
    Open,
    PartiallyFilled,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SpotPair {
    pub id: u64,
    /// Base token program (the asset being bought/sold).
    pub base: ActorId,
    /// Quote token program (USDT or USDC).
    pub quote: ActorId,
    /// Decimals of each token, verified against the VFT's own metadata at listing.
    pub base_dec: u8,
    pub quote_dec: u8,
    /// Delisted pairs reject new orders but still allow cancel/withdraw.
    pub active: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum AmmError {
    NotAdmin,
    BadParams,
    /// A pool for this token pair already exists, in either orientation.
    PoolExists,
    NoPool,
    /// Pool exists but is delisted; no new deposits or swaps.
    PoolInactive,
    /// The global pool cap is reached.
    TooManyPools,
    /// The on-chain VFT transfer failed (bad allowance/balance, or program error).
    TransferFailed,
    /// Trading is paused. Removing liquidity remains open.
    Paused,
    /// The result would be worse than the caller's stated bound.
    SlippageExceeded,
    /// Caller does not hold that many shares.
    InsufficientShares,
    /// The deposit or swap is too small to move any reserve.
    AmountTooSmall,
    /// An amount overflowed. Trapping beats a silently wrong number.
    Overflow,
    /// The token's on-chain decimals do not match the value supplied at creation.
    DecimalsMismatch,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct AmmPool {
    pub id: u64,
    pub token_a: ActorId,
    pub token_b: ActorId,
    /// Decimals of each token, verified against the VFT's own metadata at creation.
    pub dec_a: u8,
    pub dec_b: u8,
    /// Real tokens held by this program on behalf of the pool.
    pub reserve_a: u128,
    pub reserve_b: u128,
    /// Total LP shares issued, including the permanently locked minimum.
    pub total_shares: u128,
    /// Delisted pools reject deposits and swaps; removing liquidity stays open.
    pub active: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum PerpsError {
    NotAdmin,
    NotKeeper,
    BadParams,
    NoMarket,
    MarketInactive,
    StaleMark,
    LeverageTooHigh,
    InsufficientMargin,
    PositionNotFound,
    NotLiquidatable,
    BookFull,
    TransferFailed,
    NoCollateral,
    /// Opening would push this side's open interest past the market cap.
    OiCapExceeded,
    /// Trading is paused. Closing and liquidating stay open.
    Paused,
    /// The mark update deviates further from the previous mark than the bound allows.
    MarkDeviationTooLarge,
    /// The reserve is too thin relative to what it already owes to accept new risk.
    InsufficientCoverage,
    /// An amount overflowed. Trapping beats a silently wrong number.
    Overflow,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PerpMarket {
    pub id: u64,
    pub symbol: String,
    /// Mark price (arbitrary consistent units; PnL uses price ratios so the unit cancels).
    pub mark: u128,
    /// Block the mark was last published.
    pub mark_block: u32,
    pub active: bool,
    /// Open interest (sum of position notional) per side — the house's directional
    /// exposure. Capped by `max_oi` so the reserve's worst-case loss is bounded.
    pub long_oi: u128,
    pub short_oi: u128,
    /// Max open interest per side. Required at market creation: there is no
    /// unlimited default, because the safe value should not depend on an operator
    /// remembering a second call (audit M-03).
    pub max_oi: u128,
    /// Cumulative funding index in `FUNDING_SCALE` units. Rises while longs are the
    /// crowded side, falls while shorts are. Longs pay the increase, shorts receive
    /// its negation; both settle against the reserve, which is the counterparty.
    pub cum_funding: i128,
    /// Block `cum_funding` was last advanced.
    pub funding_block: u32,
}
