// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ThebookClientProgram;
impl sails_rs::client::Program for ThebookClientProgram {}
pub trait ThebookClient {
    type Env: sails_rs::client::GearEnv;
    fn orderbook(&self) -> sails_rs::client::Service<orderbook::OrderbookImpl, Self::Env>;
    fn amm(&self) -> sails_rs::client::Service<amm::AmmImpl, Self::Env>;
    fn perps(&self) -> sails_rs::client::Service<perps::PerpsImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ThebookClient
    for sails_rs::client::Actor<ThebookClientProgram, E>
{
    type Env = E;
    fn orderbook(&self) -> sails_rs::client::Service<orderbook::OrderbookImpl, Self::Env> {
        self.service(stringify!(Orderbook))
    }
    fn amm(&self) -> sails_rs::client::Service<amm::AmmImpl, Self::Env> {
        self.service(stringify!(Amm))
    }
    fn perps(&self) -> sails_rs::client::Service<perps::PerpsImpl, Self::Env> {
        self.service(stringify!(Perps))
    }
}
pub trait ThebookClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<ThebookClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ThebookClientCtors
    for sails_rs::client::Deployment<ThebookClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<ThebookClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod orderbook {
    use super::*;
    pub trait Orderbook {
        type Env: sails_rs::client::GearEnv;
        fn call_agent_service(
            &mut self,
            target: ActorId,
            payload: Vec<u8>,
            gas_limit: u64,
        ) -> sails_rs::client::PendingCall<io::CallAgentService, Self::Env>;
        fn cancel_order(
            &mut self,
            oid: u64,
        ) -> sails_rs::client::PendingCall<io::CancelOrder, Self::Env>;
        fn challenge(
            &mut self,
            opponent: ActorId,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::Challenge, Self::Env>;
        /// Move real VFT tokens from the caller into the DEX vault, crediting their
        /// internal balance. The caller must have `approve`d the DEX on the token
        /// program for at least `amount` first. Credits only after the on-chain
        /// transfer succeeds, so the internal balance stays fully token-backed.
        fn deposit(
            &mut self,
            kind: TokenKind,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::Deposit, Self::Env>;
        /// Register the caller's agent identity (name + strategy). Creates the account
        /// with ZERO balances — real value comes from claiming test tokens at the faucet
        /// and `deposit`ing them, not from free money on join. Idempotent: re-joining
        /// returns the existing balances and keeps the original identity.
        fn join(
            &mut self,
            name: String,
            strategy: AgentStrategy,
        ) -> sails_rs::client::PendingCall<io::Join, Self::Env>;
        fn market_buy(
            &mut self,
            asset: Asset,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::MarketBuy, Self::Env>;
        fn market_sell(
            &mut self,
            asset: Asset,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::MarketSell, Self::Env>;
        fn place_limit(
            &mut self,
            side: Side,
            asset: Asset,
            price: u64,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::PlaceLimit, Self::Env>;
        /// Admin-only: register the VFT program ID that backs a custodied balance.
        /// Must be set before deposit/withdraw can move real tokens for that kind.
        fn set_token(
            &mut self,
            kind: TokenKind,
            address: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetToken, Self::Env>;
        fn signal_collab(
            &mut self,
            _partner: ActorId,
            _note: String,
        ) -> sails_rs::client::PendingCall<io::SignalCollab, Self::Env>;
        fn start_autopilot(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::StartAutopilot, Self::Env>;
        fn tick(&mut self) -> sails_rs::client::PendingCall<io::Tick, Self::Env>;
        /// Withdraw real VFT tokens from the DEX vault back to the caller. Debits the
        /// internal balance first, then transfers on-chain; if the transfer fails the
        /// debit is reverted so funds are never silently lost.
        fn withdraw(
            &mut self,
            kind: TokenKind,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env>;
        /// Caller's agent identity, or None if they haven't joined. Used by the UI to
        /// decide whether to show the "Create your Agent" onboarding.
        fn get_identity(&self) -> sails_rs::client::PendingCall<io::GetIdentity, Self::Env>;
        fn get_leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetLeaderboard, Self::Env>;
        fn get_my_orders(&self) -> sails_rs::client::PendingCall<io::GetMyOrders, Self::Env>;
        fn get_orderbook(
            &self,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::GetOrderbook, Self::Env>;
        fn get_portfolio(&self) -> sails_rs::client::PendingCall<io::GetPortfolio, Self::Env>;
        fn get_status(&self) -> sails_rs::client::PendingCall<io::GetStatus, Self::Env>;
        fn get_token(
            &self,
            kind: TokenKind,
        ) -> sails_rs::client::PendingCall<io::GetToken, Self::Env>;
        /// All four token registrations as (usd, btc, eth, vara) for the UI/agents.
        fn get_tokens(&self) -> sails_rs::client::PendingCall<io::GetTokens, Self::Env>;
        fn get_trades(
            &self,
            asset: Asset,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTrades, Self::Env>;
    }
    pub struct OrderbookImpl;
    impl<E: sails_rs::client::GearEnv> Orderbook for sails_rs::client::Service<OrderbookImpl, E> {
        type Env = E;
        fn call_agent_service(
            &mut self,
            target: ActorId,
            payload: Vec<u8>,
            gas_limit: u64,
        ) -> sails_rs::client::PendingCall<io::CallAgentService, Self::Env> {
            self.pending_call((target, payload, gas_limit))
        }
        fn cancel_order(
            &mut self,
            oid: u64,
        ) -> sails_rs::client::PendingCall<io::CancelOrder, Self::Env> {
            self.pending_call((oid,))
        }
        fn challenge(
            &mut self,
            opponent: ActorId,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::Challenge, Self::Env> {
            self.pending_call((opponent, amount))
        }
        fn deposit(
            &mut self,
            kind: TokenKind,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::Deposit, Self::Env> {
            self.pending_call((kind, amount))
        }
        fn join(
            &mut self,
            name: String,
            strategy: AgentStrategy,
        ) -> sails_rs::client::PendingCall<io::Join, Self::Env> {
            self.pending_call((name, strategy))
        }
        fn market_buy(
            &mut self,
            asset: Asset,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::MarketBuy, Self::Env> {
            self.pending_call((asset, qty))
        }
        fn market_sell(
            &mut self,
            asset: Asset,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::MarketSell, Self::Env> {
            self.pending_call((asset, qty))
        }
        fn place_limit(
            &mut self,
            side: Side,
            asset: Asset,
            price: u64,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::PlaceLimit, Self::Env> {
            self.pending_call((side, asset, price, qty))
        }
        fn set_token(
            &mut self,
            kind: TokenKind,
            address: ActorId,
        ) -> sails_rs::client::PendingCall<io::SetToken, Self::Env> {
            self.pending_call((kind, address))
        }
        fn signal_collab(
            &mut self,
            _partner: ActorId,
            _note: String,
        ) -> sails_rs::client::PendingCall<io::SignalCollab, Self::Env> {
            self.pending_call((_partner, _note))
        }
        fn start_autopilot(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::StartAutopilot, Self::Env> {
            self.pending_call(())
        }
        fn tick(&mut self) -> sails_rs::client::PendingCall<io::Tick, Self::Env> {
            self.pending_call(())
        }
        fn withdraw(
            &mut self,
            kind: TokenKind,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env> {
            self.pending_call((kind, amount))
        }
        fn get_identity(&self) -> sails_rs::client::PendingCall<io::GetIdentity, Self::Env> {
            self.pending_call(())
        }
        fn get_leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetLeaderboard, Self::Env> {
            self.pending_call((limit,))
        }
        fn get_my_orders(&self) -> sails_rs::client::PendingCall<io::GetMyOrders, Self::Env> {
            self.pending_call(())
        }
        fn get_orderbook(
            &self,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::GetOrderbook, Self::Env> {
            self.pending_call((asset,))
        }
        fn get_portfolio(&self) -> sails_rs::client::PendingCall<io::GetPortfolio, Self::Env> {
            self.pending_call(())
        }
        fn get_status(&self) -> sails_rs::client::PendingCall<io::GetStatus, Self::Env> {
            self.pending_call(())
        }
        fn get_token(
            &self,
            kind: TokenKind,
        ) -> sails_rs::client::PendingCall<io::GetToken, Self::Env> {
            self.pending_call((kind,))
        }
        fn get_tokens(&self) -> sails_rs::client::PendingCall<io::GetTokens, Self::Env> {
            self.pending_call(())
        }
        fn get_trades(
            &self,
            asset: Asset,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTrades, Self::Env> {
            self.pending_call((asset, limit))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CallAgentService (target: ActorId, payload: Vec<u8>, gas_limit: u64) -> Result<Vec<u8>, super::ContractError>);
        sails_rs::io_struct_impl!(CancelOrder (oid: u64) -> Result<(), super::ContractError>);
        sails_rs::io_struct_impl!(Challenge (opponent: ActorId, amount: u64) -> Result<u32, super::ContractError>);
        sails_rs::io_struct_impl!(Deposit (kind: super::TokenKind, amount: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(Join (name: String, strategy: super::AgentStrategy) -> (u64,u64,u64,u64,));
        sails_rs::io_struct_impl!(MarketBuy (asset: super::Asset, qty: u64) -> Result<String, super::ContractError>);
        sails_rs::io_struct_impl!(MarketSell (asset: super::Asset, qty: u64) -> Result<String, super::ContractError>);
        sails_rs::io_struct_impl!(PlaceLimit (side: super::Side, asset: super::Asset, price: u64, qty: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(SetToken (kind: super::TokenKind, address: ActorId) -> Result<(), super::ContractError>);
        sails_rs::io_struct_impl!(SignalCollab (_partner: ActorId, _note: String) -> ());
        sails_rs::io_struct_impl!(StartAutopilot () -> ());
        sails_rs::io_struct_impl!(Tick () -> Result<String, super::ContractError>);
        sails_rs::io_struct_impl!(Withdraw (kind: super::TokenKind, amount: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(GetIdentity () -> Option<(String,super::AgentStrategy,)>);
        sails_rs::io_struct_impl!(GetLeaderboard (limit: u32) -> Vec<super::LeaderEntry>);
        sails_rs::io_struct_impl!(GetMyOrders () -> Vec<(u64,super::Side,super::Asset,u64,u64,u64,super::OrderStatus,)>);
        sails_rs::io_struct_impl!(GetOrderbook (asset: super::Asset) -> (Vec<(u64,u64,)>,Vec<(u64,u64,)>,));
        sails_rs::io_struct_impl!(GetPortfolio () -> (u64,u64,u64,u64,));
        sails_rs::io_struct_impl!(GetStatus () -> (u32,u64,u32,bool,u32,));
        sails_rs::io_struct_impl!(GetToken (kind: super::TokenKind) -> ActorId);
        sails_rs::io_struct_impl!(GetTokens () -> (ActorId,ActorId,ActorId,ActorId,));
        sails_rs::io_struct_impl!(GetTrades (asset: super::Asset, limit: u32) -> Vec<(u64,u64,u64,ActorId,ActorId,)>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum OrderbookEvents {
            OrderPlaced(OrderPlacedEvent),
            OrderCancelled(OrderCancelledEvent),
            Trade(TradeEvent),
        }
        impl sails_rs::client::Event for OrderbookEvents {
            const EVENT_NAMES: &'static [Route] = &["OrderPlaced", "OrderCancelled", "Trade"];
        }
        impl sails_rs::client::ServiceWithEvents for OrderbookImpl {
            type Event = OrderbookEvents;
        }
    }
}

pub mod amm {
    use super::*;
    pub trait Amm {
        type Env: sails_rs::client::GearEnv;
        fn add_liquidity(
            &mut self,
            pool_id: u64,
            amount_a: u64,
            amount_b: u64,
        ) -> sails_rs::client::PendingCall<io::AddLiquidity, Self::Env>;
        fn create_pool(
            &mut self,
            asset_a: Asset,
            asset_b: Asset,
        ) -> sails_rs::client::PendingCall<io::CreatePool, Self::Env>;
        fn remove_liquidity(
            &mut self,
            pool_id: u64,
            lp_amount: u64,
        ) -> sails_rs::client::PendingCall<io::RemoveLiquidity, Self::Env>;
        fn swap(
            &mut self,
            pool_id: u64,
            asset_in: Asset,
            amount_in: u64,
            min_amount_out: u64,
        ) -> sails_rs::client::PendingCall<io::Swap, Self::Env>;
        fn get_lp_position(
            &self,
            pool_id: u64,
            provider: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetLpPosition, Self::Env>;
        fn get_pool(&self, pool_id: u64) -> sails_rs::client::PendingCall<io::GetPool, Self::Env>;
        fn list_pools(&self) -> sails_rs::client::PendingCall<io::ListPools, Self::Env>;
    }
    pub struct AmmImpl;
    impl<E: sails_rs::client::GearEnv> Amm for sails_rs::client::Service<AmmImpl, E> {
        type Env = E;
        fn add_liquidity(
            &mut self,
            pool_id: u64,
            amount_a: u64,
            amount_b: u64,
        ) -> sails_rs::client::PendingCall<io::AddLiquidity, Self::Env> {
            self.pending_call((pool_id, amount_a, amount_b))
        }
        fn create_pool(
            &mut self,
            asset_a: Asset,
            asset_b: Asset,
        ) -> sails_rs::client::PendingCall<io::CreatePool, Self::Env> {
            self.pending_call((asset_a, asset_b))
        }
        fn remove_liquidity(
            &mut self,
            pool_id: u64,
            lp_amount: u64,
        ) -> sails_rs::client::PendingCall<io::RemoveLiquidity, Self::Env> {
            self.pending_call((pool_id, lp_amount))
        }
        fn swap(
            &mut self,
            pool_id: u64,
            asset_in: Asset,
            amount_in: u64,
            min_amount_out: u64,
        ) -> sails_rs::client::PendingCall<io::Swap, Self::Env> {
            self.pending_call((pool_id, asset_in, amount_in, min_amount_out))
        }
        fn get_lp_position(
            &self,
            pool_id: u64,
            provider: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetLpPosition, Self::Env> {
            self.pending_call((pool_id, provider))
        }
        fn get_pool(&self, pool_id: u64) -> sails_rs::client::PendingCall<io::GetPool, Self::Env> {
            self.pending_call((pool_id,))
        }
        fn list_pools(&self) -> sails_rs::client::PendingCall<io::ListPools, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddLiquidity (pool_id: u64, amount_a: u64, amount_b: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(CreatePool (asset_a: super::Asset, asset_b: super::Asset) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(RemoveLiquidity (pool_id: u64, lp_amount: u64) -> Result<(u64,u64,), super::ContractError>);
        sails_rs::io_struct_impl!(Swap (pool_id: u64, asset_in: super::Asset, amount_in: u64, min_amount_out: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(GetLpPosition (pool_id: u64, provider: ActorId) -> Option<super::LpPosition>);
        sails_rs::io_struct_impl!(GetPool (pool_id: u64) -> Option<super::Pool>);
        sails_rs::io_struct_impl!(ListPools () -> Vec<super::Pool>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum AmmEvents {
            PoolCreated(PoolCreatedEvent),
            LiquidityAdded(LiquidityAddedEvent),
            LiquidityRemoved(LiquidityRemovedEvent),
            SwapExecuted(SwapExecutedEvent),
        }
        impl sails_rs::client::Event for AmmEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "PoolCreated",
                "LiquidityAdded",
                "LiquidityRemoved",
                "SwapExecuted",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for AmmImpl {
            type Event = AmmEvents;
        }
    }
}

pub mod perps {
    use super::*;
    pub trait Perps {
        type Env: sails_rs::client::GearEnv;
        /// Close your whole position at the current mark price, settling PnL against the
        /// house reserve. Returns `(payout_cents, pnl_cents_signed)`.
        fn close_position(
            &mut self,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env>;
        /// Admin: move USD (cents) from your own balance into the house reserve that
        /// pays trader profits. Never mints — total custodied USD is unchanged.
        fn fund_reserve(
            &mut self,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::FundReserve, Self::Env>;
        /// Permissionless liquidation: if a position's equity has fallen to the
        /// maintenance margin, anyone may close it at the mark. The liquidator earns a
        /// small fee from the residual equity; the rest flows to the reserve.
        fn liquidate(
            &mut self,
            owner: ActorId,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::Liquidate, Self::Env>;
        /// Open (or add to) an isolated-margin perpetual position. Locks `margin` USD
        /// cents from your balance; position size = margin * leverage at the mark price.
        fn open_position(
            &mut self,
            asset: Asset,
            is_long: bool,
            margin: u64,
            leverage: u32,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env>;
        /// Keeper-only: publish the mark price (USD cents) for an asset. This is the
        /// price PnL and liquidations settle at — like GMX/Pyth keepers pushing a feed.
        fn set_mark_price(
            &mut self,
            asset: Asset,
            price: u64,
        ) -> sails_rs::client::PendingCall<io::SetMarkPrice, Self::Env>;
        /// Keeper convenience: push all three marks at once (BTC, ETH, VARA), each in
        /// USD cents. A zero leaves that asset's mark unchanged.
        fn set_mark_prices(
            &mut self,
            btc: u64,
            eth: u64,
            vara: u64,
        ) -> sails_rs::client::PendingCall<io::SetMarkPrices, Self::Env>;
        /// Liquidation price (USD cents) for a position, i.e. the mark at which equity
        /// hits maintenance margin. 0 if there is no such position.
        fn get_liq_price(
            &self,
            owner: ActorId,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::GetLiqPrice, Self::Env>;
        fn get_mark_price(
            &self,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::GetMarkPrice, Self::Env>;
        fn get_mark_prices(&self) -> sails_rs::client::PendingCall<io::GetMarkPrices, Self::Env>;
        /// A trader's open positions as
        /// `(asset, is_long, size, entry, margin, leverage, pnl_at_mark)`.
        fn get_positions(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env>;
        fn get_reserve(&self) -> sails_rs::client::PendingCall<io::GetReserve, Self::Env>;
    }
    pub struct PerpsImpl;
    impl<E: sails_rs::client::GearEnv> Perps for sails_rs::client::Service<PerpsImpl, E> {
        type Env = E;
        fn close_position(
            &mut self,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env> {
            self.pending_call((asset,))
        }
        fn fund_reserve(
            &mut self,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::FundReserve, Self::Env> {
            self.pending_call((amount,))
        }
        fn liquidate(
            &mut self,
            owner: ActorId,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::Liquidate, Self::Env> {
            self.pending_call((owner, asset))
        }
        fn open_position(
            &mut self,
            asset: Asset,
            is_long: bool,
            margin: u64,
            leverage: u32,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env> {
            self.pending_call((asset, is_long, margin, leverage))
        }
        fn set_mark_price(
            &mut self,
            asset: Asset,
            price: u64,
        ) -> sails_rs::client::PendingCall<io::SetMarkPrice, Self::Env> {
            self.pending_call((asset, price))
        }
        fn set_mark_prices(
            &mut self,
            btc: u64,
            eth: u64,
            vara: u64,
        ) -> sails_rs::client::PendingCall<io::SetMarkPrices, Self::Env> {
            self.pending_call((btc, eth, vara))
        }
        fn get_liq_price(
            &self,
            owner: ActorId,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::GetLiqPrice, Self::Env> {
            self.pending_call((owner, asset))
        }
        fn get_mark_price(
            &self,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::GetMarkPrice, Self::Env> {
            self.pending_call((asset,))
        }
        fn get_mark_prices(&self) -> sails_rs::client::PendingCall<io::GetMarkPrices, Self::Env> {
            self.pending_call(())
        }
        fn get_positions(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env> {
            self.pending_call((owner,))
        }
        fn get_reserve(&self) -> sails_rs::client::PendingCall<io::GetReserve, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ClosePosition (asset: super::Asset) -> Result<(u64,i64,), super::ContractError>);
        sails_rs::io_struct_impl!(FundReserve (amount: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(Liquidate (owner: ActorId, asset: super::Asset) -> Result<(), super::ContractError>);
        sails_rs::io_struct_impl!(OpenPosition (asset: super::Asset, is_long: bool, margin: u64, leverage: u32) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(SetMarkPrice (asset: super::Asset, price: u64) -> Result<(), super::ContractError>);
        sails_rs::io_struct_impl!(SetMarkPrices (btc: u64, eth: u64, vara: u64) -> Result<(), super::ContractError>);
        sails_rs::io_struct_impl!(GetLiqPrice (owner: ActorId, asset: super::Asset) -> u64);
        sails_rs::io_struct_impl!(GetMarkPrice (asset: super::Asset) -> u64);
        sails_rs::io_struct_impl!(GetMarkPrices () -> (u64,u64,u64,));
        sails_rs::io_struct_impl!(GetPositions (owner: ActorId) -> Vec<(super::Asset,bool,u64,u64,u64,u32,i64,)>);
        sails_rs::io_struct_impl!(GetReserve () -> u64);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum PerpsEvents {
            MarkPrice(MarkPriceEvent),
            Opened(PerpOpenedEvent),
            Closed(PerpClosedEvent),
        }
        impl sails_rs::client::Event for PerpsEvents {
            const EVENT_NAMES: &'static [Route] = &["MarkPrice", "Opened", "Closed"];
        }
        impl sails_rs::client::ServiceWithEvents for PerpsImpl {
            type Event = PerpsEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ContractError {
    NotAuthorized,
    NotAdmin,
    BadParams,
    JoinFirst,
    InsufficientUsd,
    InsufficientAsset,
    OrderNotFound,
    OrderAlreadyDone,
    NoLiquidity,
    NoBuyers,
    PoolExists,
    PoolNotFound,
    SameAssetPool,
    InsufficientLiquidity,
    SlippageExceeded,
    ZeroAmount,
    AgentCallFailed,
    BookFull,
    NoMarkPrice,
    LeverageTooHigh,
    PositionNotFound,
    WrongDirection,
    NotLiquidatable,
}
/// The four balances the DEX custodies, each backed by a real VFT on-chain.
/// `Usd` is a separate kind because the orderbook denominates in USD but the
/// `Asset` enum only covers the tradeable tokens (BTC/ETH/VARA).
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum TokenKind {
    Usd,
    Btc,
    Eth,
    Vara,
}
/// The trading persona a user picks when creating their agent. Display/behaviour
/// hint today; drives autopilot strategy selection in a later phase.
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum AgentStrategy {
    ArbitrageHunter,
    MarketMaker,
    Momentum,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Asset {
    BTC,
    ETH,
    VARA,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Side {
    Buy,
    Sell,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LeaderEntry {
    pub id: ActorId,
    pub name: String,
    pub strategy: AgentStrategy,
    pub usd: u64,
    pub net_worth: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum OrderStatus {
    Open,
    Partial,
    Filled,
    Cancelled,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct OrderPlacedEvent {
    pub trader: ActorId,
    pub side: Side,
    pub asset: Asset,
    pub price: u64,
    pub qty: u64,
    pub order_id: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct OrderCancelledEvent {
    pub trader: ActorId,
    pub order_id: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct TradeEvent {
    pub trade_id: u64,
    pub asset: Asset,
    pub price: u64,
    pub qty: u64,
    pub buyer: ActorId,
    pub seller: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LpPosition {
    pub pool_id: u64,
    pub provider: ActorId,
    pub amount: u64,
    pub share_a: u64,
    pub share_b: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Pool {
    pub id: u64,
    pub asset_a: Asset,
    pub asset_b: Asset,
    pub reserve_a: u64,
    pub reserve_b: u64,
    pub total_lp: u64,
    pub creator: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PoolCreatedEvent {
    pub pool_id: u64,
    pub asset_a: Asset,
    pub asset_b: Asset,
    pub creator: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LiquidityAddedEvent {
    pub pool_id: u64,
    pub provider: ActorId,
    pub amount_a: u64,
    pub amount_b: u64,
    pub lp_minted: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LiquidityRemovedEvent {
    pub pool_id: u64,
    pub provider: ActorId,
    pub amount_a: u64,
    pub amount_b: u64,
    pub lp_burned: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SwapExecutedEvent {
    pub pool_id: u64,
    pub trader: ActorId,
    pub asset_in: Asset,
    pub amount_in: u64,
    pub asset_out: Asset,
    pub amount_out: u64,
    pub fee: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MarkPriceEvent {
    pub asset: Asset,
    pub price: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PerpOpenedEvent {
    pub owner: ActorId,
    pub asset: Asset,
    pub is_long: bool,
    pub size: u64,
    pub entry: u64,
    pub margin: u64,
    pub leverage: u32,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PerpClosedEvent {
    pub owner: ActorId,
    pub asset: Asset,
    pub exit: u64,
    pub payout: u64,
    pub pnl: i64,
    pub liquidated: bool,
}
